### PR TITLE
tweak readme title header

### PR DESCRIPTION
**Pull request by dweomer**
Signed-off-by: Jacob Blain Christen <dweomer5@gmail.com>

### CODE REVIEW

**Comment by dweomer** [comment]
recheck

**Comment by dweomer** [comment]
recheck

**Comment by jlebc** [comment]
recheck

**Comment by dweomer** [comment]
recheck

**Comment by dweomer** [comment]
recheck

**Comment by dweomer** [comment]
recheck

**Comment by jlebc** [comment]
recheck

**Comment by jlebc** [comment]
recheck

**Comment by jlebc** [comment]
recheck

**Comment by dweomer** [comment]
recheck

**Pull request merged**
